### ISSUE TITLE
Add navigation to new gallery widget.

### ISSUE THREAD

**Issue by gfdesign** [elementor/elementor-gallery#15]
Dear support
Do you have intention to add navigation support to the new gallery widget?
I'd want this new widget have the prev and next arrows as the basic Elementor gallery does when user click on the images.
Looking forward to your comments.
Best regards

**Comment by kobizz** [comment]
Hi @gfdesign 

This repository is dedicated strictly to Elementor Gallery JavaScript library and not any elementor widget.

Please feel free to open a feature request at [Elementor's repository](/elementor/elementor/issues/new?template=Feature_request.md).

Thanks.
